### ISSUE TITLE
Unable to parse SCZ summary stats with sumstats_convert.py

### ISSUE THREAD

**Issue by ofrei** [precimed/python_convert#11]
```
C:\Users\Oleksandr\Documents\GitHub\python_convert>python sumstats_convert.py csv H:\ftp\ip113.ucsd.edu\GWAS_Original_Summary_Stats\PGC_SCZ\pgc5\daner_PGC_SCZ52_0513a H:\Dropbox\analysis\2016_09_September_19_LDScoreRegression\1m\1m.ref SCZ.csv
Interpreting column names from summary statistics file as follows:
A2:     Allele 2, interpreted as non-ref allele for signed sumstat.
SE:     standard error of the effect size
P:      p-Value
INFO:   INFO score (imputation quality; higher --> better imputation)
BP:     Base-pair position
SNP:    Variant ID (e.g., rs number)
CHR:    Chromosome number
A1:     Allele 1, interpreted as ref allele for signed sumstat.
OR:     Odds ratio (1 --> no effect; above 1 --> A1 is risk increasing)

Skip the remaining columns (HetISqt, HetChiSq, HetPVa, ngt, Direction, FRQ_A_35476, FRQ_U_46839, HetDf).
Reading reference file H:\Dropbox\analysis\2016_09_September_19_LDScoreRegression\1m\1m.ref...
Reference dict contains 1190321 snps.
Reading summary statistics file H:\ftp\ip113.ucsd.edu\GWAS_Original_Summary_Stats\PGC_SCZ\pgc5\daner_PGC_SCZ52_0513a...
100000 lines processed
200000 lines processed
300000 lines processed
400000 lines processed
500000 lines processed
600000 lines processed
700000 lines processed
800000 lines processed
900000 lines processed
1000000 lines processed
1100000 lines processed
1200000 lines processed
1300000 lines processed
1400000 lines processed
1500000 lines processed
1600000 lines processed
1700000 lines processed
1800000 lines processed
1900000 lines processed
2000000 lines processed
2100000 lines processed
Traceback (most recent call last):
  File "pandas\parser.pyx", line 1084, in pandas.parser.TextReader._convert_tokens (pandas\parser.c:12580)
TypeError: Cannot cast array from dtype('O') to dtype('float64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sumstats_convert.py", line 271, in <module>
    args.func(args)
  File "sumstats_convert.py", line 129, in make_csv
    for i, chunk in enumerate(reader):
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 795, in __next__
    return self.get_chunk()
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 836, in get_chunk
    return self.read(nrows=size)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 815, in read
    ret = self._engine.read(nrows)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1314, in read
    data = self._reader.read(nrows)
  File "pandas\parser.pyx", line 805, in pandas.parser.TextReader.read (pandas\parser.c:8748)
  File "pandas\parser.pyx", line 839, in pandas.parser.TextReader._read_low_memory (pandas\parser.c:9208)
  File "pandas\parser.pyx", line 904, in pandas.parser.TextReader._read_rows (pandas\parser.c:10022)
  File "pandas\parser.pyx", line 1011, in pandas.parser.TextReader._convert_column_data (pandas\parser.c:11397)
  File "pandas\parser.pyx", line 1092, in pandas.parser.TextReader._convert_tokens (pandas\parser.c:12775)
ValueError: cannot safely convert passed user dtype of <f8 for object dtyped data in column 8
```

**Comment by ofrei** [comment]
Fixed long time ago
