### ISSUE TITLE
Loading 23andme sumstats to 11M template

### ISSUE THREAD

**Issue by ofrei** [precimed/python_convert#23]
This problem is specific to 23andme sumstats, and happens only in 11M SNPs template. I'll leave it for now - nothing urgent to worry about.

````
Traceback (most recent call last):
  File "/home/oleksandr/precimed/python_convert/sumstats.py", line 1302, in <module>
    args.func(args, log)
  File "/home/oleksandr/precimed/python_convert/sumstats.py", line 691, in make_mat
    effect_sign *= not_ref_effect
TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

Analysis finished at Thu Jan 25 08:27:14 2018
Total time elapsed: 12.0m:18.44s
Traceback (most recent call last):
  File "/home/oleksandr/precimed/python_convert/sumstats.py", line 1302, in <module>
    args.func(args, log)
  File "/home/oleksandr/precimed/python_convert/sumstats.py", line 691, in make_mat
    effect_sign *= not_ref_effect
TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
make: *** [/space/syn03/1/data/oleksandr/SynGen2/11015833/SUMSTAT/23andMe_AGREE_2016.mat] Error 1
```

**Comment by ofrei** [comment]
```
Call:
./sumstats.py mat \
        --force  \
        --sumstats /space/syn03/1/data/GWAS/SUMSTAT/STD/23andMe_AGREE_2016.csv.gz \
        --keep-all-cols  \
        --ref /space/syn03/1/data/oleksandr/SynGen2/11015833/all_chromosomes_multiallelic_replaced_with_AT.ref \
        --out /space/syn03/1/data/oleksandr/SynGen2/11015833/SUMSTAT/23andMe_AGREE_2016.mat
Beginning analysis at Thu Jan 25 08:14:55 2018 by oleksandr, host pip31.ucsd.edu

```
