### ISSUE TITLE
sumstats.py commands may crash when --out is a pipe

### ISSUE THREAD

**Issue by ofrei** [precimed/python_convert#33]
```
python ~/users/gunnarr/PythonPackages/python_convert/sumstats.py zscore --sumstats PGC_SCZ_2014_EUR.csv | python ~/users/gunnarr/PythonPackages/python_convert/sumstats.py qc --exclude-ranges 6:26000000-34000000 --max-or 1e37 | python ~/users/gunnarr/PythonPackages/python_convert/sumstats.py neff --drop --factor 4 --out PGC_SCZ_2014_EUR_qc_noMHZ.csv --force
Traceback (most recent call last):
  File "~/users/gunnarr/PythonPackages/python_convert/sumstats.py", line 2138, in <module>
Traceback (most recent call last):
  File "~/users/gunnarr/PythonPackages/python_convert/sumstats.py", line 2138, in <module>
    log = Logger(args.log if args.log else (args.out + '.log' if (args.out != '-') else None), 'a' if args.log_append else 'w')mixer/issues/
  File "~/users/gunnarr/PythonPackages/python_convert/sumstats.py", line 2058, in __init__
    log = Logger(args.log if args.log else (args.out + '.log' if (args.out != '-') else None), 'a' if args.log_append else 'w')
  File "~/users/gunnarr/PythonPackages/python_convert/sumstats.py", line 2058, in __init__
    os.remove(fh + '.error')
TypeError: unsupported operand tmixer/issues/mixer/issues/ype(s) for +: 'NoneType' and 'str'
    os.remove(fh + '.error')
TypeError: unsupported operanmixer/issues/mixer/issues/mixer/issues/d type(s) for +: 'NoneType' and 'str'
```

**Comment by ofrei** [comment]
Fixed in 5dcbc20f0891e7dfbadc8bcdbfa313fe5e00ecc2
