### ISSUE TITLE
Error report when using fdrmat2csv.py:  Length of values does not match length of index

### ISSUE THREAD

**Issue by WQ-CHENG** [precimed/python_convert#38]
- python version: 2.7
- 9279485_ref.bim downloaded from NIRD GWAS sumstats directory.
- /result.mat was generated from pleioFDR.
- python packages used in fdrmat2csv.py were already installed.

Here are the details:
```
python /opt/python_convert/fdrmat2csv.py result.mat 9279485_ref.bim
Load result.mat
Load 9279485_ref.bim
/opt/python_convert/fdrmat2csv.py:14: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  ref=pd.read_table(reffile, delim_whitespace=True)
Traceback (most recent call last):
  File "/opt/python_convert/fdrmat2csv.py", line 15, in <module>
    ref['FDR']=sumstats['fdrmat']
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 3370, in __setitem__
    self._set_item(key, value)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 3445, in _set_item
    value = self._sanitize_column(key, value)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 3630, in _sanitize_column
    value = sanitize_index(value, self.index, copy=False)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals/construction.py", line 519, in sanitize_index
    raise ValueError('Length of values does not match length of index')
ValueError: Length of values does not match length of index

```

**Comment by ofrei** [comment]
9279485_ref is deprecated, we've moved to 9545380_ref/9545380.ref
It's unfortunate that both templates have ~9M SNPs. The one with 9.5M
correct. The one with 9.2M is legacy (deprecated)
